#### SEML and SLURM config

seml:
  executable: main.py
  name: CIFAR10_LeNet5_global_noise_layer_repetition
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options_template: rivulet_gpu
  experiments_per_job: 8
  sbatch_options:
    begin: now       # dummy parameter
    nice: 0


#### Experiment config

fixed:
  general:
    num_epochs: 300
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None
  noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
      enable_in_training: True

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 1
    step: 1

global_repetition_BN:
  fixed:
    noise_settings.default.GaussStd: 1.95
    noise_settings.default.enable_in_training: True
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5-BN
    model.LeNet.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20

global_repetition_noBN:
  fixed:
    noise_settings.default.GaussStd: 1.62
    noise_settings.default.enable_in_training: True
  grid:
    model.LeNet.conf_name:
      type: choice
      options:
        - LeNet5
    model.LeNet.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20



layer_repetition_with_BN_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_log10_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,1,2,2,2,1,2,2,2,1,3,2,1,3,3,1,]
        - [5,2,3,4,4,1,3,3,4,1,4,4,1,4,4,1,]
        - [9,3,6,6,6,1,6,6,6,2,6,6,2,6,7,2,]
        - [12,5,8,8,9,2,8,8,9,2,9,9,2,9,9,3,]
        - [18,7,12,12,12,3,12,12,12,3,12,12,3,13,13,4,]
        - [36,13,24,24,24,5,24,24,24,7,25,24,6,25,26,9,]


layer_repetition_with_BN_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_sqrt_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,1,2,2,2,1,3,2,1,3,3,1,]
        - [4,3,3,3,4,1,3,3,4,1,4,4,1,4,4,2,]
        - [7,5,6,6,6,1,6,6,6,2,6,6,1,6,7,3,]
        - [9,7,8,9,9,1,8,9,9,2,9,9,1,9,9,4,]
        - [13,10,12,12,13,1,12,12,13,3,13,13,1,13,13,6,]
        - [26,20,25,25,25,1,25,25,25,5,26,25,2,26,26,13,]


layer_repetition_with_BN_inverse_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [10,1,1,2,2,1,1,1,2,1,2,2,1,2,2,1,]
        - [16,1,2,2,3,1,2,2,3,1,3,3,1,3,4,1,]
        - [28,1,4,4,5,1,4,4,5,1,5,5,1,5,6,1,]
        - [40,1,6,6,6,1,6,6,7,1,7,6,1,8,9,1,]
        - [57,2,9,9,9,1,9,9,9,1,10,9,1,11,13,1,]
        - [116,3,18,18,19,1,17,18,19,1,20,19,1,22,26,2,]


layer_repetition_with_BN_inverse_lin_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
        - [32,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,]
        - [58,1,1,1,2,1,1,1,2,1,2,2,1,2,3,1,]
        - [83,1,2,2,2,1,2,2,2,1,3,2,1,3,4,1,]
        - [120,1,3,3,3,1,3,3,3,1,3,3,1,5,6,1,]
        - [244,1,6,6,7,1,5,6,7,1,7,6,1,9,12,1,]

layer_repetition_with_BN_inverse_square_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
        - [33,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
        - [65,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
        - [97,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
        - [145,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]
        - [305,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,]

layer_repetition_with_BN_inverse_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [7,1,2,2,2,1,2,2,2,1,2,2,1,2,2,1,]
        - [10,2,3,3,3,1,3,3,3,1,3,3,1,3,4,2,]
        - [16,3,5,5,5,2,5,5,5,3,5,5,2,5,6,3,]
        - [22,4,7,7,7,3,7,7,7,4,7,7,3,8,8,4,]
        - [32,6,10,10,10,5,10,10,10,5,10,10,5,11,11,5,]
        - [64,12,20,20,20,9,20,20,20,10,20,20,9,22,23,11,]

layer_repetition_with_BN_layer_sort_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,1,1,1,2,3,1,3,2,3,2,3,1,2,1,2,]
        - [6,1,1,2,3,4,2,5,3,5,3,5,1,2,1,4,]
        - [9,1,2,4,5,7,3,8,5,8,6,9,1,4,2,6,]
        - [13,2,2,5,7,10,4,11,7,12,8,12,1,6,3,9,]
        - [19,2,4,7,9,14,6,15,11,16,12,18,1,8,5,13,]
        - [38,5,7,14,19,28,12,31,21,33,24,35,2,16,9,26,]

layer_repetition_with_BN_layer_sort_inverse_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,1,1,1,2,1,2,1,3,1,4,1,1,1,2,]
        - [14,1,1,1,2,3,1,4,2,5,2,7,1,1,1,2,]
        - [24,1,2,2,3,5,2,6,3,8,3,12,1,2,2,4,]
        - [33,2,2,3,4,7,3,8,4,11,5,17,2,3,3,5,]
        - [47,3,3,4,5,9,4,12,6,16,7,24,3,5,4,8,]
        - [95,6,7,9,10,19,8,24,12,32,13,47,6,9,7,16,]

layer_repetition_with_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,1,1,1,2,3,1,3,2,3,2,3,1,2,1,3,]
        - [5,1,1,2,3,4,2,5,3,5,3,5,1,3,1,4,]
        - [9,1,2,3,4,7,3,8,6,8,6,9,1,4,2,7,]
        - [12,2,3,5,6,9,5,11,8,11,8,12,2,6,3,9,]
        - [18,2,4,7,9,13,7,16,11,16,11,18,2,9,4,13,]
        - [36,4,9,13,18,27,13,31,22,31,22,36,4,18,9,27,]

layer_repetition_with_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,1,1,1,2,3,1,3,2,3,2,3,1,2,1,3,]
        - [5,1,2,2,3,4,2,4,3,5,3,5,1,2,2,4,]
        - [8,3,3,4,5,6,4,7,5,8,5,8,1,4,3,6,]
        - [11,4,4,5,7,9,6,9,7,11,7,11,2,6,4,9,]
        - [16,5,5,8,11,13,8,13,10,16,10,16,3,8,5,13,]
        - [31,11,11,16,21,26,16,26,21,31,21,31,5,16,11,26,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,1,1,1,1,2,1,3,1,3,1,6,1,1,1,2,]
        - [9,1,1,2,2,3,2,4,2,4,2,9,1,2,1,3,]
        - [15,2,2,2,3,5,2,7,4,7,4,15,2,3,2,5,]
        - [21,3,3,3,4,7,3,10,5,10,5,21,3,4,3,7,]
        - [29,4,4,5,6,10,5,15,7,15,7,29,4,6,4,10,]
        - [59,7,8,10,12,20,10,29,15,29,15,59,7,12,8,20,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5-BN
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.95
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,1,1,1,2,2,1,2,2,4,2,4,1,1,1,2,]
        - [7,1,1,2,2,4,2,4,2,7,2,7,1,2,1,3,]
        - [11,2,2,3,4,6,3,6,4,11,4,11,2,3,2,6,]
        - [16,3,3,4,6,8,4,8,5,16,5,16,3,4,3,8,]
        - [23,4,4,6,8,11,6,11,8,23,8,23,4,6,4,11,]
        - [46,9,9,11,15,23,11,23,15,46,15,46,8,11,9,23,]









layer_repetition_no_BN_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_log10_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,3,2,2,2,2,2,2,2,1,1,]
        - [4,4,4,3,3,3,3,3,3,4,1,1,]
        - [7,6,6,5,5,5,5,6,6,6,2,1,]
        - [9,8,9,8,7,8,7,8,8,8,3,1,]
        - [13,12,12,11,10,11,10,11,11,12,5,2,]
        - [27,24,24,22,20,21,20,22,22,24,10,4,]


layer_repetition_no_BN_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_sqrt_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,2,2,2,2,2,2,1,]
        - [4,3,4,3,3,3,3,3,3,3,3,1,]
        - [6,6,6,5,5,5,5,5,6,6,4,1,]
        - [8,8,8,8,7,7,7,8,8,8,6,1,]
        - [11,11,11,11,11,11,11,11,11,11,9,1,]
        - [23,22,23,22,22,22,22,22,22,22,17,1,]


layer_repetition_no_BN_inverse_sqrt_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,3,3,1,1,1,1,2,2,3,1,1,]
        - [8,4,4,2,2,2,2,3,3,4,1,1,]
        - [13,7,8,4,3,4,3,4,5,7,1,1,]
        - [19,10,11,6,4,5,4,6,7,10,1,1,]
        - [27,14,16,8,6,8,6,9,10,14,1,1,]
        - [54,28,32,16,12,16,13,19,20,28,1,1,]


layer_repetition_no_BN_inverse_lin_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,2,3,1,1,1,1,1,1,2,1,1,]
        - [14,4,5,1,1,1,1,1,2,4,1,1,]
        - [24,6,8,2,1,2,2,3,3,7,1,1,]
        - [34,9,12,3,2,3,2,4,4,9,1,1,]
        - [49,13,17,4,2,4,3,6,7,13,1,1,]
        - [99,26,34,9,5,8,6,11,13,27,1,1,]

layer_repetition_no_BN_inverse_square_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [13,1,1,1,1,1,1,1,1,1,1,1,]
        - [22,1,3,1,1,1,1,1,1,2,1,1,]
        - [41,3,5,1,1,1,1,1,1,3,1,1,]
        - [60,4,7,1,1,1,1,1,1,5,1,1,]
        - [88,6,10,1,1,1,1,1,2,7,1,1,]
        - [181,12,22,2,1,1,1,2,3,13,1,1,]


layer_repetition_no_BN_inverse_log10_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,3,2,1,2,2,2,2,2,1,1,]
        - [7,4,4,3,2,2,2,3,3,4,1,1,]
        - [11,6,7,4,4,4,4,5,5,6,2,2,]
        - [16,8,9,6,5,6,6,7,7,9,3,2,]
        - [22,12,13,9,8,9,8,10,10,12,4,3,]
        - [45,24,27,18,15,17,16,19,20,25,8,6,]

layer_repetition_no_BN_layer_sort_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,3,1,3,1,1,3,2,2,2,1,1,]
        - [5,5,1,5,2,2,4,3,3,4,1,1,]
        - [9,8,2,8,3,4,7,5,5,6,2,1,]
        - [13,11,3,12,4,5,10,8,6,9,2,1,]
        - [18,15,5,17,6,8,14,11,9,12,3,2,]
        - [37,31,9,34,12,15,28,22,18,25,6,3,]

layer_repetition_no_BN_layer_sort_inverse_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [7,2,1,4,1,1,2,1,1,2,1,1,]
        - [12,4,1,6,1,1,3,2,2,2,1,1,]
        - [19,6,2,10,2,2,5,3,3,4,2,2,]
        - [27,9,3,14,3,3,7,5,4,5,2,2,]
        - [39,13,4,19,4,5,10,6,6,8,3,3,]
        - [77,26,8,39,9,10,19,13,11,15,7,6,]

layer_repetition_no_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,1,3,1,2,3,2,2,2,1,1,]
        - [5,4,2,5,2,3,4,3,3,3,1,1,]
        - [9,7,3,9,3,4,7,6,4,6,1,1,]
        - [12,10,4,12,4,6,10,8,6,8,2,2,]
        - [17,14,6,17,6,9,14,11,9,11,3,3,]
        - [34,29,11,34,11,17,29,23,17,23,6,6,]

layer_repetition_no_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,1,3,2,2,2,2,2,2,1,1,]
        - [5,5,1,5,2,2,4,4,2,4,1,1,]
        - [8,8,2,8,4,4,6,6,4,6,2,2,]
        - [11,11,3,11,6,6,8,8,6,8,3,3,]
        - [16,16,4,16,8,8,12,12,8,12,4,4,]
        - [32,32,8,32,16,16,24,24,16,24,8,8,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,2,1,5,1,1,2,2,1,2,1,1,]
        - [7,4,2,7,2,2,4,2,2,2,1,1,]
        - [12,6,3,12,3,3,6,4,3,4,2,2,]
        - [17,9,3,17,3,4,9,6,4,6,3,3,]
        - [25,12,5,25,5,6,12,8,6,8,4,4,]
        - [49,25,10,49,10,12,25,16,12,16,8,8,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.LeNet.conf_name: LeNet5
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.62
  grid:
    model.LeNet.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,4,1,4,1,1,2,2,1,2,1,1,]
        - [6,6,1,6,2,2,3,3,2,3,1,1,]
        - [10,10,2,10,3,3,5,5,3,5,2,2,]
        - [13,13,3,13,5,5,7,7,5,7,3,3,]
        - [19,19,5,19,6,6,10,10,6,10,5,5,]
        - [38,38,10,38,13,13,19,19,13,19,10,10,]

