#### SEML and SLURM config

seml:
  executable: main.py
  name: CIFAR10_mlp_TFC_global_noise_layer_repetition
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options_template: rivulet_gpu
  experiments_per_job: 10
  sbatch_options:
    begin: now       # dummy parameter
    nice: 0


#### Experiment config

fixed:
  general:
    num_epochs: 200
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: CIFAR10
  model:
    model_class: MLP
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None
  noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
      enable_in_training: True

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 1
    step: 1

global_repetition_BN:
  fixed:
    noise_settings.default.GaussStd: 2.11
  grid:
    model.MLP.conf_name:
      type: choice
      options:
        - RL_TFC
    model.MLP.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20

global_repetition_noBN:
  fixed:
    noise_settings.default.GaussStd: 2.89
  grid:
    model.MLP.conf_name:
      type: choice
      options:
        - RL_TFC-noBN
    model.MLP.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20

layer_repetition_with_BN_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_log10_scaling
    noise_settings.default.GaussStd: 2.11
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,1,3,3,1,2,2,1,2,3,1,]
        - [5,2,4,4,2,3,3,1,3,4,2,]
        - [8,3,6,6,3,6,6,2,6,6,3,]
        - [11,5,9,9,4,8,8,2,8,9,4,]
        - [16,6,13,13,6,12,11,3,12,12,6,]
        - [31,13,25,25,12,24,23,6,24,24,13,]

layer_repetition_with_BN_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_sqrt_scaling
    noise_settings.default.GaussStd: 2.11
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,2,2,1,2,2,2,]
        - [4,2,4,4,2,3,3,1,4,4,2,]
        - [6,4,6,6,4,6,6,1,6,6,4,]
        - [9,6,9,9,5,8,8,1,8,8,6,]
        - [13,8,12,12,8,12,12,1,12,12,8,]
        - [25,17,25,24,15,24,24,1,24,24,17,]

layer_repetition_with_BN_inverse_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 2.11
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,1,2,2,1,2,2,1,2,2,1,]
        - [10,1,4,4,1,3,2,1,3,3,1,]
        - [18,1,7,6,1,5,5,1,5,5,1,]
        - [25,1,10,9,1,7,7,1,7,8,1,]
        - [36,2,14,13,1,10,9,1,11,11,2,]
        - [72,4,27,26,3,20,19,1,21,23,4,]

layer_repetition_with_BN_inverse_lin_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 2.11
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [11,1,2,1,1,1,1,1,1,1,1,]
        - [18,1,3,2,1,1,1,1,2,2,1,]
        - [32,1,5,4,1,2,2,1,3,3,1,]
        - [45,1,7,6,1,4,3,1,4,4,1,]
        - [66,1,9,9,1,5,4,1,6,7,1,]
        - [134,1,19,18,1,11,9,1,12,13,1,]

layer_repetition_with_BN_inverse_square_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 2.11
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [12,1,1,1,1,1,1,1,1,1,1,]
        - [23,1,1,1,1,1,1,1,1,1,1,]
        - [45,1,1,1,1,1,1,1,1,1,1,]
        - [67,1,1,1,1,1,1,1,1,1,1,]
        - [98,1,2,2,1,1,1,1,1,1,1,]
        - [202,1,4,4,1,1,1,1,2,2,1,]

layer_repetition_with_BN_inverse_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 2.11
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,1,3,2,1,2,2,1,2,2,1,]
        - [7,2,4,3,2,3,3,1,3,3,2,]
        - [11,3,6,6,3,5,5,2,5,6,3,]
        - [16,4,8,8,4,7,7,3,8,8,4,]
        - [22,6,12,12,6,10,10,5,10,11,6,]
        - [45,12,24,23,11,21,20,9,21,22,12,]





layer_repetition_no_BN_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_log10_scaling
    noise_settings.default.GaussStd: 2.89
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,3,1,1,]
        - [5,3,3,3,3,4,2,1,]
        - [7,5,5,6,5,7,3,2,]
        - [10,7,7,8,8,9,5,2,]
        - [15,10,10,11,11,13,7,3,]
        - [29,21,21,22,21,27,13,6,]

layer_repetition_no_BN_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_sqrt_scaling
    noise_settings.default.GaussStd: 2.89
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,2,2,1,]
        - [4,3,3,3,3,4,3,1,]
        - [6,6,5,6,6,6,4,1,]
        - [9,8,8,8,8,8,6,1,]
        - [12,12,11,12,12,12,8,1,]
        - [25,23,23,23,23,25,17,1,]

layer_repetition_no_BN_inverse_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 2.89
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,1,1,2,1,3,1,1,]
        - [9,2,2,2,2,5,1,1,]
        - [15,3,3,4,4,9,1,1,]
        - [21,5,5,5,5,13,1,1,]
        - [30,7,7,8,7,18,2,1,]
        - [60,14,14,16,15,37,3,1,]

layer_repetition_no_BN_inverse_lin_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 2.89
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [7,1,1,1,1,3,1,1,]
        - [13,1,1,1,1,5,1,1,]
        - [24,1,1,2,1,9,1,1,]
        - [33,2,2,2,2,13,1,1,]
        - [48,3,2,3,3,19,1,1,]
        - [98,5,5,7,6,37,1,1,]

layer_repetition_no_BN_inverse_square_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 2.89
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,1,1,1,1,1,1,]
        - [16,1,1,1,1,2,1,1,]
        - [30,1,1,1,1,4,1,1,]
        - [44,1,1,1,1,6,1,1,]
        - [64,1,1,1,1,10,1,1,]
        - [134,1,1,1,1,20,1,1,]

layer_repetition_no_BN_inverse_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 2.89
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,1,2,2,3,1,1,]
        - [6,3,2,3,3,4,2,1,]
        - [10,4,4,5,5,7,3,2,]
        - [14,6,6,7,6,10,4,3,]
        - [20,9,9,9,9,14,6,4,]
        - [41,17,17,19,18,28,11,9,]

