#### SEML and SLURM config

seml:
  executable: main.py
  name: MNIST_mlp_TFC_global_noise_layer_repetition
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter
    nice: 0


#### Experiment config

fixed:
  general:
    num_epochs: 100
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: MNIST
  model:
    model_class: MLP
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None
  noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
      enable_in_training: True

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 1
    step: 1

global_repetition_BN:
  fixed:
    noise_settings.default.GaussStd: 1.57
    noise_settings.default.enable_in_training: True
  grid:
    model.MLP.conf_name:
      type: choice
      options:
        - RL_TFC
    model.MLP.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20

global_repetition_noBN:
  fixed:
    noise_settings.default.GaussStd: 1.69
    noise_settings.default.enable_in_training: True
  grid:
    model.MLP.conf_name:
      type: choice
      options:
        - RL_TFC-noBN
    model.MLP.repetition_config.global:
      type: choice
      options:
        - 1
        - 2
        - 3
        - 5
        - 7
        - 10
        - 20


layer_repetition_with_BN_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_log10_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,2,2,2,1,2,2,1,2,3,1,]
        - [6,2,4,4,1,3,3,1,4,4,1,]
        - [10,4,6,6,1,6,6,1,6,7,2,]
        - [13,6,9,9,2,9,8,1,9,9,2,]
        - [19,8,13,13,3,12,12,1,13,13,3,]
        - [38,16,26,25,5,24,24,3,26,27,6,]

layer_repetition_with_BN_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_sqrt_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,3,2,1,2,2,1,2,3,1,]
        - [4,3,4,4,1,4,3,1,4,4,1,]
        - [7,6,6,6,2,6,6,1,6,6,3,]
        - [9,8,9,9,2,9,9,1,9,9,3,]
        - [13,11,13,13,4,12,12,1,13,13,5,]
        - [26,23,26,25,8,25,25,1,25,26,10,]

layer_repetition_with_BN_inverse_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,2,1,1,1,1,1,2,2,1,]
        - [15,1,3,2,1,2,2,1,2,3,1,]
        - [26,1,4,4,1,4,4,1,4,5,1,]
        - [37,2,6,6,1,5,5,1,6,7,1,]
        - [54,2,9,8,1,7,7,1,9,11,1,]
        - [110,5,17,17,1,15,14,1,17,22,1,]

layer_repetition_with_BN_inverse_lin_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [12,1,1,1,1,1,1,1,1,1,1,]
        - [23,1,1,1,1,1,1,1,1,1,1,]
        - [44,1,1,1,1,1,1,1,1,2,1,]
        - [64,1,2,1,1,1,1,1,2,2,1,]
        - [92,1,2,2,1,2,2,1,2,4,1,]
        - [188,1,5,4,1,4,3,1,5,7,1,]

layer_repetition_with_BN_inverse_square_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [12,1,1,1,1,1,1,1,1,1,1,]
        - [23,1,1,1,1,1,1,1,1,1,1,]
        - [45,1,1,1,1,1,1,1,1,1,1,]
        - [67,1,1,1,1,1,1,1,1,1,1,]
        - [100,1,1,1,1,1,1,1,1,1,1,]
        - [210,1,1,1,1,1,1,1,1,1,1,]

layer_repetition_with_BN_inverse_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,2,1,1,1,1,1,2,2,1,]
        - [14,2,3,2,1,2,2,1,2,3,1,]
        - [23,2,4,4,2,4,4,2,4,4,2,]
        - [33,4,6,6,2,5,5,2,6,6,2,]
        - [47,5,8,8,3,8,7,3,8,9,4,]
        - [94,10,16,16,7,15,15,6,16,18,7,]

layer_repetition_with_BN_layer_sort_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,1,3,1,3,2,2,3,1,2,1,]
        - [5,1,4,2,4,3,3,5,1,3,2,]
        - [9,2,7,3,7,5,4,8,1,6,3,]
        - [13,2,10,4,9,7,6,12,1,8,5,]
        - [18,3,15,5,13,10,8,17,2,12,7,]
        - [37,7,30,10,27,20,17,33,3,23,13,]

layer_repetition_with_BN_layer_sort_inverse_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [7,1,2,1,2,1,1,4,1,1,1,]
        - [11,1,4,1,3,2,2,5,1,2,1,]
        - [18,2,6,2,4,3,3,9,2,4,2,]
        - [25,3,9,3,6,4,4,13,2,5,3,]
        - [37,4,12,4,9,6,5,18,3,7,5,]
        - [73,7,24,8,18,12,10,37,7,15,9,]

layer_repetition_with_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,1,3,1,3,2,2,3,1,2,1,]
        - [5,2,4,2,4,3,2,5,1,3,2,]
        - [8,3,7,3,7,5,4,8,1,5,4,]
        - [11,4,9,4,9,7,6,11,2,8,6,]
        - [16,5,13,5,14,11,8,16,3,11,8,]
        - [32,11,27,11,27,21,16,32,5,22,16,]

layer_repetition_with_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,1,3,1,2,2,2,3,1,2,2,]
        - [5,1,5,2,3,3,2,5,1,4,2,]
        - [7,2,7,4,6,6,4,7,2,6,4,]
        - [11,3,10,5,8,8,5,11,3,8,5,]
        - [15,4,15,8,11,11,8,15,4,11,8,]
        - [30,8,30,15,23,23,15,30,8,23,15,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [5,1,2,1,2,1,1,5,1,2,1,]
        - [7,1,4,1,4,2,2,7,1,2,2,]
        - [11,2,6,2,6,4,3,12,2,4,3,]
        - [16,3,8,3,8,6,4,16,3,6,4,]
        - [23,5,11,5,11,8,6,23,4,8,6,]
        - [46,9,23,9,23,16,12,46,8,16,12,]

layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC
    general.experiment_name: layer_repetition_with_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.57
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,1,3,1,2,2,1,4,1,2,1,]
        - [5,1,6,2,3,3,2,5,1,3,2,]
        - [9,2,9,3,5,5,3,9,2,5,3,]
        - [13,3,13,4,6,7,4,13,3,7,4,]
        - [18,5,18,6,9,9,6,19,5,9,6,]
        - [37,9,37,12,18,18,12,37,9,19,12,]




layer_repetition_no_BN_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_log10_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,2,2,2,2,1,1,]
        - [5,4,4,3,3,3,1,1,]
        - [9,7,6,5,5,5,2,1,]
        - [12,9,9,7,7,8,3,1,]
        - [17,13,13,11,9,11,5,1,]
        - [34,26,25,22,19,22,10,2,]

layer_repetition_no_BN_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_sqrt_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,2,2,2,2,2,2,1,]
        - [4,4,3,3,3,3,3,1,]
        - [6,6,6,6,5,6,4,1,]
        - [8,8,8,8,8,8,7,1,]
        - [12,12,12,11,11,12,9,1,]
        - [24,24,23,23,23,23,19,1,]

layer_repetition_no_BN_inverse_sqrt_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_sqrt_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [8,2,1,1,1,1,1,1,]
        - [14,3,2,1,1,1,1,1,]
        - [24,5,4,2,1,2,1,1,]
        - [34,7,5,3,2,3,1,1,]
        - [50,10,8,4,2,4,1,1,]
        - [100,21,16,8,5,8,1,1,]

layer_repetition_no_BN_inverse_lin_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_lin_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,1,1,1,1,1,1,]
        - [17,1,1,1,1,1,1,1,]
        - [33,1,1,1,1,1,1,1,]
        - [48,2,1,1,1,1,1,1,]
        - [70,3,2,1,1,1,1,1,]
        - [145,6,4,1,1,1,1,1,]

layer_repetition_no_BN_inverse_square_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_square_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [9,1,1,1,1,1,1,1,]
        - [17,1,1,1,1,1,1,1,]
        - [33,1,1,1,1,1,1,1,]
        - [49,1,1,1,1,1,1,1,]
        - [73,1,1,1,1,1,1,1,]
        - [153,1,1,1,1,1,1,1,]

layer_repetition_no_BN_inverse_log10_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_inverse_log10_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [8,2,1,1,1,1,1,1,]
        - [13,2,2,2,1,2,1,1,]
        - [21,4,4,3,2,3,2,1,]
        - [30,6,5,4,3,4,2,2,]
        - [43,8,7,6,5,6,3,2,]
        - [86,17,15,11,9,11,6,5,]

layer_repetition_no_BN_layer_sort_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,1,2,2,1,1,]
        - [5,5,4,2,3,3,1,1,]
        - [9,8,7,3,6,4,2,1,]
        - [12,11,9,5,8,6,3,2,]
        - [18,16,13,7,11,9,4,2,]
        - [36,31,27,13,22,18,9,4,]

layer_repetition_no_BN_layer_sort_inverse_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [6,3,2,1,1,1,1,1,]
        - [9,4,3,2,2,2,1,1,]
        - [15,7,5,2,4,3,2,2,]
        - [21,10,7,3,5,4,3,3,]
        - [29,15,10,5,7,6,4,4,]
        - [59,29,20,10,15,12,8,7,]

layer_repetition_no_BN_layer_sort_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,2,2,2,2,1,1,]
        - [5,5,4,2,4,2,1,1,]
        - [8,8,6,4,6,4,2,2,]
        - [11,11,8,6,8,6,3,3,]
        - [16,16,12,8,12,8,4,4,]
        - [32,32,24,16,24,16,8,8,]

layer_repetition_no_BN_layer_sort_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,2,2,2,2,1,1,]
        - [4,4,4,3,3,3,2,1,]
        - [7,7,7,5,5,5,2,2,]
        - [10,10,10,7,6,7,3,3,]
        - [14,14,14,9,9,10,5,5,]
        - [28,28,28,19,19,19,10,9,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_two_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [4,4,2,1,2,1,1,1,]
        - [6,6,3,2,3,2,1,1,]
        - [10,10,5,3,5,3,2,2,]
        - [13,13,7,5,7,5,3,3,]
        - [19,19,10,6,10,6,5,5,]
        - [38,38,19,13,19,13,10,10,]

layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling:
  fixed:
    model.MLP.conf_name: RL_TFC-noBN
    general.experiment_name: layer_repetition_no_BN_layer_sort_inverse_bins_of_three_scaling
    noise_settings.default.GaussStd: 1.69
  grid:
    model.MLP.repetition_config.layer_wise_mapped:
      type: choice
      options:
        - [3,3,3,2,2,1,1,1,]
        - [5,5,5,2,2,2,2,1,]
        - [8,8,8,4,4,4,2,2,]
        - [11,11,11,5,5,5,4,4,]
        - [16,15,15,8,8,8,5,5,]
        - [31,31,31,16,15,16,10,10,]
