#### SEML and SLURM config

seml:
  executable: main.py
  name: MNIST_mlp_TFC_global_noise_layer_repetition
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 100
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: MNIST
  model:
    model_class: MLP
    criterion: CrossEntropyLoss
    MLP.repetition_config:
      global: 10
      layer_wise_mapped:
        0: 17
        1: 13
        2: 13
        3: 11
        4: 9
        5: 11
        6: 5
        7: 1
  noise_settings.layer_wise: None
  noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
      GaussStd: 1.69
      enable_in_training: True

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 1
    step: 1
  model.MLP.conf_name:
    type: choice
    options:
      # - RL_TFC
      - RL_TFC-noBN
      # - RL_TFC-BN-noNoise

# # no_noise:
# #   fixed:
# #     noise_settings.default.noise_type: NoNoise

# gauss_add:
#   fixed:
#     noise_settings.default:
#       noise_type: GaussAdd
#       GaussMean: 0.0
#   grid:
#     noise_settings.default:
#       GaussStd:
#         type: loguniform
#         min: 1e-2
#         max: 1e+2
#         num: 17
#       enable_in_training:
#         type: choice
#         options:
#           - 1
#           - 0
