#### SEML and SLURM config

seml:
  executable: main.py
  name: GSC2_CNN_global_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  experiments_per_job: 1
  sbatch_options:
    begin: now       # dummy parameter
    mem: 6G
    cpus-per-task: 1
    gres: gpu:1


#### Experiment config

fixed:
  general:
    num_epochs: 800
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 0.0005
  data:
    dataset: GSC2_TF
    batch_size: 512
  model:
    model_class: CNN_HE
    criterion: CrossEntropyLoss
    weight_criterion: True
  noise_settings.layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 1
    step: 1
  model.CNN_HE.conf_name:
    type: choice
    options:
      - CNN-S-BN

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add_clamped:
  fixed:
    general.weight_clamping:
      min: -1
      max: 1
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 1
          - 0
