#### SEML and SLURM config

seml:
  executable: main.py
  name: LeNet5_diff_novar
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 1  # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 2 #6
  sbatch_options:
    begin: now       # dummy parameter
    nice: 0
    gres: gpu:1
    time: 0-36:00
    mem: 15G
    cpus-per-task: 4
    partition: brook
    exclude: ''


#### Experiment config

fixed:
  general:
    num_epochs: 500
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
    #weight_decay: 5e-4 # L2 regularization, weight_decay in SGD and Adam
    #gradient_reg: 1e-2
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings:
    layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 1
    step: 1
  model.LeNet.conf_name:
    type: choice
    options:
      - LeNet5

gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd_in_training:
        type: choice
        options:
          - 0.5
          - 1.5
      GaussStd:
        type: choice
        options:
          - 0.5
          - 1.5
      enable_in_training:
        type: choice
        options:
          - 0
