#### SEML and SLURM config

seml:
  executable: main.py
  name: LeNet5_global_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 3  # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 5 #6
  sbatch_options:
    begin: now       # dummy parameter
    nice: 1000
    gres: gpu:1
    time: 0-36:00
    mem: 25G
    cpus-per-task: 20
    partition: octane
    exclude: 'csg-octane[01-05]'


#### Experiment config

fixed:
  general:
    num_epochs: 500
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
    #weight_decay: 5e-4 # L2 regularization, weight_decay in SGD and Adam
    #gradient_reg: 1e-2
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings:
    layer_wise: None
    is_incremental: False
    is_overshooting: False

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 5
    step: 1
  model.LeNet.conf_name:
    type: choice
    options:
      - LeNet5
  optimizer.gradient_reg:
    type: choice
    options:
      - 1e-1
      - 1e-2
      - 1e-3

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 0