#### SEML and SLURM config

seml:
  executable: main.py
  name: LeNet5_comb
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 5 # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 5 #6
  sbatch_options:
    begin: now       # dummy parameter
    nice: 1000
    gres: gpu:1
    time: 0-36:00
    mem: 35G
    cpus-per-task: 30
    partition: rivulet
    #nodelist: csg-rivulet03
    #exclude: 'csg-octane[01-02],'
    exclude: ''
#### Experiment config

fixed:
  general:
    num_epochs: 500
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet_QAT
    criterion: CrossEntropyLoss
  noise_settings:
    layer_wise: None
    is_incremental: False
  general.enable_sam: True
  general.is_adaptive: True

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 5
    step: 1
  model.LeNet_QAT.conf_name:
    type: choice
    options:
      - LeNet5
  model.LeNet_QAT.bit_width:
    type: choice
    options:
      - 8
  model.LeNet_QAT.scale:
    type: choice
    options:
      - 1
      - 2
      - 8
      - 32
      - 64
  general.sam_rho:
    type: choice
    options:
      - 0.05
      - 0.1
      - 0.5
      - 1.5
      - 2.5
      - 5


no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise


gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 0
