#### SEML and SLURM config

seml:
  executable: main.py
  name: CIFAR10_LeNet5_awp
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 6  # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 4 #6
  sbatch_options:
    begin: now       # dummy parameter
    nice: 1000
    gres: gpu:1
    time: 0-36:00
    mem: 24G
    cpus-per-task: 20
    partition: rivulet
    exclude: 'octane[001-002],ceg-rivulet01'
#### Experiment config

fixed:
  general:
    num_epochs: 300
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss
  noise_settings:
    layer_wise: None
    is_incremental: False

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 3
    step: 1
  model.LeNet.conf_name:
    type: choice
    options:
      - LeNet5
  general.adv_settings:
    type: choice
    options:
      - PGD
  general.awp_settings:
    type: choice
    options:
      - True

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise


gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 0
          - 1

