#### SEML and SLURM config

seml:
  executable: main.py
  name: LeNet5_param_sigma
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 8  # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 3 #6
  sbatch_options:
    begin: now       # dummy parameter
    nice: 1000
    gres: gpu:1
    time: 0-36:00
    mem: 15G
    cpus-per-task: 12
    partition: rivulet
    exclude: ''


#### Experiment config

fixed:
  general:
    num_epochs: 150
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
    #weight_decay: 1e-4 # L2 regularization, weight_decay in SGD and Adam
  data:
    dataset: CIFAR10
  model:
    model_class: LeNet
    criterion: CrossEntropyLoss

  noise_settings:
    layer_wise: None
    is_incremental: False


grid:
  general.repeat_number:
    type: range
    min: 0
    max: 3
    step: 1
  model.LeNet.conf_name:
    type: choice
    options:
      - LeNet5

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add:
  fixed:
    noise_settings.param_sigma:
      is_enabled: True
      lr: 1e-3
      num_epochs: 10
      init_Std: 0.1
      clean_model: ./models_noisy/lenet-500-GaussModule.pth
      T: 1
      b: 1
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 1