#### SEML and SLURM config

seml:
  executable: main.py
  name: VGG_global_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 5 # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 3
  sbatch_options:
    begin: now       # dummy parameter
    nice: 1000
    gres: gpu:1
    time: 0-36:00
    mem: 36G
    cpus-per-task: 24
    partition: rivulet
    exclude: ''


#### Experiment config

fixed:
  general:
    num_epochs: 500
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
    #weight_decay: 5e-4
  data:
    dataset: CIFAR10
  model:
    model_class: VGG
    criterion: CrossEntropyLoss
    VGG:
      dropout_fc: 0.5
      #dropout_conv: 0.1
  noise_settings:
    layer_wise: None
    is_incremental: True # necessary
  model.distill:
    is_enabled: False
    teacher: ./models_noisy/vgg-300.pth

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 5
    step: 1
  model.VGG.conf_name:
    type: choice
    options:
      - VGG11-noBN
  optimizer.gradient_reg:
    type: choice
    options:
      - 1e-1
      - 1e-2
      - 1e-3

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 0

