#### SEML and SLURM config

seml:
  executable: main.py
  name: VGG_qat
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 8 # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 3
  sbatch_options:
    begin: now       # dummy parameter
    nice: 1000
    gres: gpu:1
    time: 0-36:00
    mem: 30G
    cpus-per-task: 24
    partition: rivulet
    exclude: ''
    #nodelist: csg-rivulet01

#
#exclude: 'octane[001-002]'


#### Experiment config

fixed:
  general:
    num_epochs: 500
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-4
  data:
    dataset: CIFAR10
  model:
    model_class: VGG_QAT
    criterion: CrossEntropyLoss
  noise_settings:
    layer_wise: None
    is_incremental: True #necessary, model is very sensitive to noise

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 5
    step: 1
  model.VGG_QAT.conf_name:
    type: choice
    options:
      - VGG11-noBN
  model.VGG_QAT.bit_width:
    type: choice
    options:
      - 4
      - 8
      - 16
  model.VGG_QAT.scale:
    type: choice
    options:
      - None
      - 0.5
      - 1
      - 2
      - 3
      - 4
      - 8

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 0

