#### SEML and SLURM config

seml:
  executable: main.py
  name: vgg_adv
  output_dir: logs
  project_root_dir: ../..

slurm:
  max_simultaneous_jobs: 1 # Restrict number of simultaneously running jobs per job array
  experiments_per_job: 5
  sbatch_options:
    begin: now       # dummy parameter
    nice: 1000
    gres: gpu:1
    time: 0-36:00
    mem: 40G
    cpus-per-task: 25
    partition: rivulet
    exclude: 'octane[001-002]'


#### Experiment config

fixed:
  general:
    num_epochs: 500
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
    #weight_decay: 1e-4 # L2 regularization, weight_decay in SGD and Adam, 5e-4 is too large
  data:
    dataset: CIFAR10
  model:
    model_class: VGG
    criterion: CrossEntropyLoss
    VGG:
      dropout_fc: 0.5
      #dropout_conv: 0.1
  noise_settings:
    layer_wise: None
    is_incremental: True # necessary
  #general.enable_sam: True
  #general.is_adaptive: True
  general.adv_type: PGD

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 5
    step: 1
  model.VGG.conf_name:
    type: choice
    options:
      - VGG11-noBN
  #general.sam_rho:
  #  type: choice
  #  options:
  #    - 0.75
  #    - 1
  #    - 1.5
  #    - 2
  #    - 2.5
  #    - 3

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 0
