#### SEML and SLURM config

seml:
  executable: main.py
  name: CIFAR10_vgg_no_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  experiments_per_job: 2
  sbatch_options:
    begin: now       # dummy parameter
    cpus-per-task: 2
    mem: 20G
    time: 0-04:00


#### Experiment config

fixed:
  general:
    num_epochs: 300
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: CIFAR10
  model:
    model_class: VGG
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 20
    step: 1
  model.VGG.conf_name:
    type: choice
    options:
      - VGG11
      - VGG11-noBN
      - VGG11-BN-noNoise

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

no_noise_clamped:
  fixed:
    general.weight_clamping:
      min: -1
      max: 1
    noise_settings.default.noise_type: NoNoise
