#### SEML and SLURM config

seml:
  executable: main.py
  name: vgg_no_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 50
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: MNIST
  model:
    model_class: VGG
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 10
    step: 1
  model.VGG.conf_name:
    type: choice
    options:
      - VGG11_mnist
      - VGG11_mnist-noBN
      - VGG11_mnist-BN-noNoise

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

no_noise_clamped:
  fixed:
    general.weight_clamping:
      min: -1
      max: 1
    noise_settings.default.noise_type: NoNoise
