#### SEML and SLURM config

seml:
  executable: main.py
  name: vgg_global_noise
  output_dir: logs
  project_root_dir: ../..

slurm:
  sbatch_options:
    begin: now       # dummy parameter


#### Experiment config

fixed:
  general:
    num_epochs: 50
  optimizer:
    optimizer_type: Adam
    lr_scheduler: CosineAnnealingLR
    lr: 1e-3
  data:
    dataset: MNIST
  model:
    model_class: VGG
    criterion: CrossEntropyLoss
  noise_settings.layer_wise: None

grid:
  general.repeat_number:
    type: range
    min: 0
    max: 10
    step: 1
  model.VGG.conf_name:
    type: choice
    options:
      - VGG11_mnist
      - VGG11_mnist-noBN
      - VGG11_mnist-BN-noNoise

no_noise:
  fixed:
    noise_settings.default.noise_type: NoNoise

gauss_add_clamped:
  fixed:
    general.weight_clamping:
      min: -1
      max: 1
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 1
          - 0

gauss_add:
  fixed:
    noise_settings.default:
      noise_type: GaussAdd
      GaussMean: 0.0
  grid:
    noise_settings.default:
      GaussStd:
        type: loguniform
        min: 1e-2
        max: 1e+2
        num: 17
      enable_in_training:
        type: choice
        options:
          - 1
          - 0

gauss_mul:
  fixed:
    noise_settings.default:
      noise_type: GaussMul
      GaussMean: 1.0
  grid:
    noise_settings.default:
      GaussStd:
        type: uniform
        min: 0
        max: 2.
        num: 21
      enable_in_training:
        type: choice
        options:
          - 1
          - 0
